[package]
name = "posting"
version = "0.1.0"
authors = ["Noel Martin <noel.martin.07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
patricia_tree = "0.1.8"
