[package]
name = "inforetrust"
version = "0.1.0"
authors = ["Noel Martin <n.martin@qwant.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< Updated upstream
=======
patricia_tree = "0.1.8"
actix = "0.7"
>>>>>>> Stashed changes
